image: docker:latest

stages:
  - build-bundle
  - build-image
  - build-number-update

variables:
  BUILD_NUMBER: 1.0.0.$BUILD_COUNTER
  GITLAB_HOST: "https://gitlab.nsys.org"

before_script:
  - echo BUILD_NUMBER=$BUILD_NUMBER

build-bundle:
  image: maven:3-jdk-8
  stage: build-bundle
  before_script:
    - echo BUILD_NUMBER=$BUILD_NUMBER
    - export NSYS_OPTS="-Dbuild.number=${BUILD_NUMBER}"
  script: mvn clean resources:resources install deploy $NSYS_OPTS -U
  artifacts:
    paths:
      - nsys-demo-bundle/target/nsys-demo-bundle-${BUILD_NUMBER}.zip

build-nsys-demo:
  stage: build-image
  dependencies:
    - build-bundle
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PWD"
  script:
    - cd docker-images/nsys-demo
    - cp `pwd`/../scripts/nsys-demo-installer.sh ./
    - cp nsys-demo-bundle/target/nsys-demo-bundle-${BUILD_NUMBER}.zip ./nsys-demo-bundle.zip
    - docker build --pull --no-cache -t nsys/nsys-demo .
    - docker push nsys/nsys-demo

build-nsys-demo-node:
  stage: build-image
  dependencies:
    - build-bundle
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PWD"
  script:
    - cd docker-images/nsys-demo-node
    - cp `pwd`/../scripts/nsys-demo-installer.sh ./
    - cp nsys-demo-bundle/target/nsys-demo-bundle-${BUILD_NUMBER}.zip ./nsys-demo-bundle.zip
    - docker build --pull --no-cache -t nsys/nsys-demo-node .
    - docker push nsys/nsys-demo-node

build-number-update:
  image: ubuntu:16.04
  stage: build-number-update
  before_script:
    - apt-get update -y && apt-get install curl -y
  script:
    - export COUNTER=$((BUILD_COUNTER+1))
    - curl -X PUT -H "PRIVATE-TOKEN:$GITLAB_TOKEN" $GITLAB_HOST/api/v4/projects/10/variables/BUILD_COUNTER -F value=$COUNTER
