image: docker:latest

stages:
  - build-bundle

variables:
  BUILD_NUMBER: 1.0.0.$CI_PIPELINE_ID

before_script:
  - echo BUILD_NUMBER=$BUILD_NUMBER

build-bundle:
  image: maven:3-jdk-8
  stage: build-bundle
  before_script:
    - echo BUILD_NUMBER=$BUILD_NUMBER
    - export NSYS_OPTS="-Dbuild.number=${BUILD_NUMBER}"
  script: mvn clean resources:resources install deploy $NSYS_OPTS -U
  artifacts:
    paths:
      - nsys-bundle/target/nsys-demo-bundle-${BUILD_NUMBER}.zip
